apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: security-hall-of-shame-prod-letsencrypt
spec:
  secretName: security-hall-of-shame-prod-letsencrypt
  dnsNames:
  - securityhallofshame.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - securityhallofshame.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
